
1. Univariate Plot data:

```{r, message=FALSE, results='hide'}
library(rio)

location='https://github.com/chuhanl/Visual-Analytics/raw/main/'
file='ACS%202019%20weighted%20subsample.dta'
link=paste0(location,file)
mydata=import(link)
absoluteT=table(mydata$marst,
                exclude = 'nothing')
newNames=c('Married, spouse present','Married, spouse absent','Separated','Divorced','Widowed','Never married/single')
names(absoluteT)=newNames
prop.table(absoluteT)
propT=prop.table(absoluteT)*100
tableFreq=as.data.frame(absoluteT)
names(tableFreq)=c("MaritalStatus","Count")
tableFreq$Percent=as.vector(propT)
```

Saves as a file:
```{r}
saveRDS(tableFreq,file = 'acs2019marstat.rds')
```


2. Bivariate Plot data:

```{r}
SexMarst=table(mydata$marst,mydata$sex)
SexMarst[1,1]=SexMarst[1,1]+SexMarst[2,1]
SexMarst[1,2]=SexMarst[1,2]+SexMarst[2,2]
SexMarst[3,1]=SexMarst[3,1]+SexMarst[4,1]
SexMarst[3,2]=SexMarst[3,2]+SexMarst[4,2]
SexMarst=SexMarst[-2,]
SexMarst=SexMarst[-3,]
newRowNames=c('Married','Separated/divorced','Widowed','Never married/single')
newColNames=c('Male','Female')
rownames(SexMarst) <- newRowNames
colnames(SexMarst) <- newColNames
library(magrittr)
SexMarst_mgCol=prop.table(SexMarst,
                            margin = 2)%>%round(.,3)
SexMarstDF=as.data.frame(SexMarst)
names(SexMarstDF)=c("MaritalStatus","Sex","Counts")
SexMarstDF$Percent=as.data.frame(SexMarst_mgCol)[,3]
SexMarstDF$MaritalStatus=factor(SexMarstDF$MaritalStatus,
                           levels=c('Widowed','Separated/divorced','Married','Never married/single'))
```

Saves as a file:
```{r}
saveRDS(SexMarstDF,file = 'SexMarstDF.rds')
```


3. Map data:

```{r}
linkCSV='https://github.com/chuhanl/Deliverable-3/raw/main/wwmarstatus.csv'
mydata=read.csv(linkCSV)
mydata$DIV_S=as.vector(scale(mydata$Divrate))
mydata$RATIO_S=as.vector(scale(mydata$divtomarRatio))
```

```{r}
# cluster the data using pam
set.seed(123)

library(cluster)
vars=c('DIV_S','RATIO_S')

distMatrix=cluster::daisy(mydata[,vars])
          
res.pam=cluster::pam(x=distMatrix,
                     k = 3,
                     cluster.only = F)

mydata$cluster=as.factor(res.pam$clustering)
```

```{r}
theVars=c('DIV_S','RATIO_S','cluster')
aggregate(.~cluster,
          data=mydata[,theVars],
          FUN=median)

mydata$cluster=factor(mydata$cluster,
                           levels=c(1,2,3),
                           labels=c("low","mid","high"), 
                           ordered=T)
```

```{r}
# open the map and add the data to the map
linkMap="https://github.com/EvansDataScience/VAforPM_Spatial/raw/main/worldMap.geojson" 

library(sf)
mapWorld=read_sf(linkMap)

mapWorldVars=merge(mapWorld,
                   mydata, 
                   by='ISO3')
```

Saves as a file:
```{r}
saveRDS(mapWorldVars,file = 'mapWorldVars.rds')
```